import { ENV } from "./_core/env";

export interface ContentGenerationRequest {
  contentType: "article" | "social_post" | "product_description";
  topic: string;
  contentLength: "short" | "medium" | "long";
  tone: string;
  language: string;
}

function buildSystemPrompt(contentType: string, tone: string): string {
  const basePrompt = `You are a professional content writer specializing in creating high-quality, engaging content. 
Your tone should be ${tone} and professional. 
Generate original, unique, and valuable content that resonates with the audience.`;

  const typeSpecific = {
    article: "Write a comprehensive blog article with an engaging introduction, well-structured body paragraphs, and a compelling conclusion.",
    social_post: "Write an engaging social media post that is concise, attention-grabbing, and encourages interaction.",
    product_description: "Write a compelling product description that highlights key features and benefits while encouraging purchase.",
  };

  return `${basePrompt}\n\nContent Type: ${typeSpecific[contentType as keyof typeof typeSpecific] || basePrompt}`;
}

function buildUserPrompt(request: ContentGenerationRequest): string {
  const lengthGuide = {
    short: "approximately 200-300 words",
    medium: "approximately 500-700 words",
    long: "approximately 1000-1500 words",
  };

  return `Generate ${request.contentType.replace("_", " ")} about "${request.topic}" in ${lengthGuide[request.contentLength]}. Language: ${request.language}. Tone: ${request.tone}.`;
}

export async function generateContentWithForgeAPI(request: ContentGenerationRequest): Promise<string> {
  try {
    // Check if Forge API credentials are available
    if (!ENV.forgeApiUrl || !ENV.forgeApiKey) {
      console.warn("Forge API credentials not configured, using fallback");
      return generateFallbackContent(request);
    }

    const systemPrompt = buildSystemPrompt(request.contentType, request.tone);
    const userPrompt = buildUserPrompt(request);

    const response = await fetch(`${ENV.forgeApiUrl}/v1/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ENV.forgeApiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.7,
        max_tokens: request.contentLength === "long" ? 1500 : request.contentLength === "medium" ? 700 : 300,
      }),
    });

    if (!response.ok) {
      console.error("Forge API error:", response.status, response.statusText);
      return generateFallbackContent(request);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || generateFallbackContent(request);
  } catch (error) {
    console.error("Error calling Forge API:", error);
    return generateFallbackContent(request);
  }
}

function generateFallbackContent(request: ContentGenerationRequest): string {
  const templates = {
    article: `# ${request.topic}\n\nThis is a professional article about ${request.topic}. In a production environment, this would be generated by our AI system using advanced language models.\n\n## Introduction\nOur AI-powered content generation system creates high-quality, engaging content tailored to your needs.\n\n## Key Points\n- Professional quality content\n- Customizable tone and style\n- Fast generation times\n- SEO-optimized output\n\n## Conclusion\nLeverage the power of AI to create amazing content for your business.`,
    
    social_post: `🚀 Discover the power of ${request.topic}! 
    
Our AI-powered platform helps you create engaging content in seconds. Perfect for marketers, creators, and entrepreneurs.

#AI #ContentCreation #Innovation #${request.topic.replace(/\\s+/g, "")}`,
    
    product_description: `Experience the excellence of ${request.topic}.

Our product combines cutting-edge technology with user-friendly design to deliver exceptional value. Whether you're a professional or just getting started, our solution is perfect for your needs.

Key Features:
✓ Easy to use
✓ Powerful capabilities
✓ Reliable performance
✓ Excellent support

Transform your workflow with ${request.topic} today.`,
  };

  return templates[request.contentType] || templates.article;
}
